### ISSUE TITLE
Compare mode: feedback and todo

### ISSUE THREAD

**Issue by md-mq** [polyaxon/polyaxon#1438]
## Slack discussion

> Hi everyone we just deployed the comparison view to cloud with the diff and the changes modes, please let us know if you have any feedback before final release:

<img width="1127" alt="Screenshot 2021-10-25 at 10 37 34" src="https://user-images.githubusercontent.com/1261626/138667319-604e4f1f-b9d9-486f-99c0-017615e0f5f7.png">

<img width="1438" alt="Screenshot 2021-10-25 at 10 38 16" src="https://user-images.githubusercontent.com/1261626/138667330-08b7706a-1f25-4d18-834e-e3fc8a60c1f3.png">

## Missing features

 * [x] Single column with `Diff: on` does not show any row, this mode should only perform checks if there are at least 2 runs to compare.
 * [ ] UI should provide a way to set the objective of a metric or a param (increasing or decreasing), if a loss has a `-0.05` diff, the arrow should be green not red.
 * [ ] Diff for nested objects
